name: Welcome New Issues

on:
  issues:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Send Welcome Message
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.SMIRK235_TOKEN }}
        script: |
          const issueNumber = context.payload.issue.number;
          const welcomeMessage = `
          Hi @${context.payload.issue.user.login},

          Thanks for opening this issue! We'll get back to you soon.

          Best,
          smirk235
          `;
          await github.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issueNumber,
            body: welcomeMessage
          });
