name: Welcome New Issues

on:
  issues:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Updated Node.js version

    - name: Create package.json
      run: |
        echo '{}' > package.json
    - name: Install octokit
      run: npm install @octokit/rest

    - name: Send Welcome Message
      env:
        GITHUB_TOKEN: ${{ secrets.SMIRK235_TOKEN }}
      run: |
        node << 'EOF'
        const { Octokit } = require('@octokit/rest');
        const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
        const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
        const issueNumber = require(process.env.GITHUB_EVENT_PATH).issue.number;
        const welcomeMessage = `
        Hi @${require(process.env.GITHUB_EVENT_PATH).issue.user.login},
        Thanks for opening this issue! We'll get back to you soon.
        Best,
        smirk235
        `;
        octokit.issues.createComment({
          owner,
          repo,
          issue_number: issueNumber,
          body: welcomeMessage
        }).catch(err => console.error('Failed to create comment:', err));
        EOF
